#!/usr/bin/env bash

# Seleccion del fondo de manera random
lista=(~/wallpapers/*)
numero=$((RANDOM % "${#lista[@]}"))
imagen_random="${lista[numero]}"

awww img "$imagen_random" --transition-type center --transition-duration 2

