backend = "glx";

# Radio de las esquinas de las ventanas
corner-radius = 6;

# Configuracion de la sombra de las ventanas
shadow = true;
shadow-radius = 15;
shadow-opacity = 0.5;

# Configuracion del desenfoque de transparencias
blur-method = "dual_kawase";
